# fly.toml app configuration file
app = 'catalogo'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000  # MUDANÃ‡A AQUI
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "3000"  # Adicionar isso pode ajudar

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1